### ISSUE TITLE
Info: processing `PHP': Please wait...

### ISSUE THREAD

**Issue by markkasaboski** [SublimeCodeIntel/SublimeCodeIntel#173]
On my machine CodeIntel will work for about 5 minutes and then it stops responding. Just sits on "Info: processing `PHP': please wait..."

I've tried dumping the db several times. Every time it reindexes, it'll work for about 5 minutes and then the same message. 

See log below.

It is building up a fairly large db (160 MB) as I do have 5 very large project checkouts. Any way I can get it to only scan the one I'm currently working on? It looks like it's scanning the entire system for PHP files. Is that correct?

ST2 v2.0.1 bulid 2217
OS X Lion 10.7.4

Starting logging SublimeCodeIntel rev GIT-unknown (1346257295) on Wed Aug 29 14:44:53 2012
# ==========================================================================================Starting logging SublimeCodeIntel rev GIT-unknown (1346257295) on Wed Aug 29 14:44:53 2012
- Info: Invalid language: Plain text. Available: JavaScript, Mason, XBL, XUL, RHTML, SCSS, Python, HTML, Ruby, Python3, XML, XSLT, Django, HTML5, Perl, CSS, Less, Smarty, Node.js, Tcl, TemplateToolkit, PHP
- Info: processing `PHP': please wait...
- Info: Invalid language: Plain text. Available: JavaScript, Mason, XBL, XUL, RHTML, SCSS, Python, HTML, Ruby, Python3, XML, XSLT, Django, HTML5, Perl, CSS, Less, Smarty, Node.js, Tcl, TemplateToolkit, PHP
- Info: processing `HTML': please wait...
  Updating indexes for 'HTML'... The first time this can take a while.
  Doing CodeIntel for 'HTML' (hold on)...
  Done 'HTML' CodeIntel! Full CodeIntel took 369ms
  Doing CodeIntel for 'HTML' (hold on)...
  Done 'HTML' CodeIntel! Full CodeIntel took 1ms
  Doing CodeIntel for 'HTML' (hold on)...
  Done 'HTML' CodeIntel! Full CodeIntel took 2ms
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...
- Info: processing `PHP': please wait...

**Comment by ccbility** [comment]
Just shut down "codeintel_live", make the setting like
{
	"codeintel_live": false
}
Everything is more faster !
