### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by lapega** [SublimeCodeIntel/SublimeCodeIntel#194]
I was looking an alternative more light-weight to Aptana, and  just discovered Sublime Text 2 yesterday.
The package SublimeCodeIntel is absolutly necesary to replace Aptana, but it doesn't work. 
Spent almost 4hours reading forums and 'the internet' to get it working, but nothing.

When I get to github I see the last activity is 4months old, so the question is: is project dead?

Thanks a lot!

**Comment by binarious** [comment]
@Kronuz I think it's appropriate to re-ask the question. Is this project dead? Do you need any help? There hasn't been any progress for a while now.

**Comment by Kronuz** [comment]
Well, it's not dead... but I definitely could use a lot of help. There are always many people just complaining, but not much (next to none) help. SublimeCodeIntel sort of works for me and my team as it is, and the lack of time and busyness make me neglect new releases and fixes.

**Comment by venox** [comment]
What would be the next steps to do? Port the current Version for CodeIntel from Komodo?
