### ISSUE TITLE
HTML suggestion issue

### ISSUE THREAD

**Issue by babakness** [SublimeCodeIntel/SublimeCodeIntel#279]
Keep on suggesting I close a closed tag over and over again, ie
<html>
<head>
<title>Foobar</title> (I press enter here, it suggest "title> (element)" and will keep suggesting it.*).

This issue affects HTML in PHP as well. Very annoying. Is there a way to turn of live autocomplete just for HTML? I've tried the language specific configurations but I can't seem to disable auto complete that way.

Thanks for suggestions.
- \- ps, Why does it suggest closing HTML tags without the "</" part of it!?

**Comment by technophyle** [comment]
Yeah the bug is really annoying. I had to uninstall the plugin.
