### ISSUE TITLE
Python @property decorator completion inserts src of the decorator

### ISSUE THREAD

**Issue by anentropic** [SublimeCodeIntel/SublimeCodeIntel#290]
When editing a python file if I start typing: `@prop`... the first option in the completion drop down is `@property` as it should be.

But unfortunately if I press enter it then inserts the source of the decorator into the document instead of just completing the word for me!

eg suddenly I get this:

```
@def foo():
        doc = "The foo property."
        def fget(self):
            return self._foo
        def fset(self, value):
            self._foo = value
        def fdel(self):
            del self._foo
        return locals()
    foo = property(**foo())
```

instead of

```
@property
```

**Comment by Nearoo** [comment]
Does someone know where I can find an explanation for this snippet? I've been programming python for a while, yet I have no idea how on earth this snippet works...
