### ISSUE TITLE
CSS autocompletion

### ISSUE THREAD

**Issue by tanc** [SublimeCodeIntel/SublimeCodeIntel#3]
Hi, loving the development so far of the plugin. With latest updates of this plugin and sublime text its really coming together. One thing I noticed is that the css autocompletion is not working very nicely. Is there a way to turn off codeintel for css files?

Problems are autocompletions trigger when typing the minus character so for example, when typing 'font-size' I get an automatic autocompletion of 'font-weight' instead when I get to the minus character. This makes typing css very difficult.

Thanks!

**Comment by antoniomerlin** [comment]
I've tried using `Preferences>Package-Settings>sublimecodeintel>settings-default`
and removing css from `"codeintel_enabled_languages"` but still no luck
