### ISSUE TITLE
codeintel_scan_exclude_dir options for JavaScript is not working

### ISSUE THREAD

**Issue by silentroach** [SublimeCodeIntel/SublimeCodeIntel#372]
Seems like it is always equals to "/build/" :[

Found this in diffs: https://github.com/SublimeCodeIntel/SublimeCodeIntel/commit/295ad7283b579de0b01f13accbb596366c0ba2c6#diff-877f3602ce140547da1a6710a67bc5e0R636

**Comment by wizza-smile** [comment]
I fixed this in my fork of this project!
find it here:
https://github.com/wizza-smile/SublimeCodeIntel3
