### ISSUE TITLE
Django - from django.db import models - ST3/W8.1x64

### ISSUE THREAD

**Issue by aWakeParks** [SublimeCodeIntel/SublimeCodeIntel#389]
I just tried to create a new model in django. There is just one single problem, the plugin still works fine with every other import. Maybe someone can confirm this bug, even on other platforms?
________________________________________________
Case 1 - Here is where the bug happens:

from django.db import models

class SignUp(models.Model):
"""docstring"""
    username = models. 

Then I only get SignUp and __doc__ as auto-completion:
________________________________________________
Case 2 - no problem:

from django.db import models as md

class SignUp(md.Model):
"""docstring"""
    username = md.

Here I get all auto-completion recommendations.
______________________________________________
Case 3 - no problem:
import django.db

class SignUp(django.db.models.Model):
"""docstring"""
    username = django.db.models.

Same here as well as in case 2.

___________________________________________

Can somebody reproduce that bug?

**Comment by Kronuz** [comment]
Yes, sounds a like a reasonable explanation. I'll consider the alternative as it shouldn't be using the current file as the source of autocompletion in that case.
