### ISSUE TITLE
TypeError: run_() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by etiennejcharles** [SublimeCodeIntel/SublimeCodeIntel#401]
The autocompletion doesn't seem to work on particular languages. 

When I try to set the sublime to a language syntax called "Xiki", which was added to my user settings and try to type snippets, I believe they should be appearing but that isn't the case. 

When I tried to reset the Sublime CodeIntel plugin, I got this error, and wondered if this is related. 

TypeError: run_() takes from 1 to 2 positional arguments but 3 were given

I love the work you do on this plugin it's simply amazing and saves me ours, 

I am using sublime text 3. 
Thanks for the help !

**Comment by rleger** [comment]
Same here, removed conflicting key bindings with FindKeyConflics, removed and reinstalled the package since. I still get the same error..

**Comment by rleger** [comment]
I got some errors on install.. :

```
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/ordereddict.py", line 23, in <module>
    from UserDict import DictMixin
ImportError: No module named 'UserDict'
reloading plugin SublimeCodeIntel.SublimeCodeIntel
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 126, in reload_plugin
    el.on_activated(v)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1442, in on_activated
    settings_manager.update()
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1378, in update
    self.updateLanguageSpecificSettings()
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/SublimeCodeIntel/SublimeCodeIntel.py", line 1385, in updateLanguageSpecificSettings
    for language in codeintel_language_settings:
TypeError: 'NoneType' object is not iterable
found 31 files for base name Default.sublime-keymap
found 3 files for base name Default.sublime-mousemap
found 27 files for base name Main.sublime-menu
theme loaded
loading pointer bindings
```

**Comment by joostrijneveld** [comment]
I found conflicts, but my key bindings are conflicting with default bindings of Sublime.. Is there anything I can do about that, seeing as I cannot edit those defaults? It appears not to override them correctly when the number of arguments is different, since I can easily override them with the `paste` command, but not with anything that requires arguments.

**Comment by lukebarton** [comment]
KK

**Comment by oldbasilbear** [comment]
Can anyone advise whether this issue has been fixed? I'm having problems with javascript completion in particular. Thanks .

**Comment by TomasBarry** [comment]
Any solution to this? I have no key binding conflicts with Sublime Code Intel.

**Comment by etiennejcharles** [comment]
Well that's sad, seems like that even after 4 years this haven't been fixed, my solution was to switch to vscode, I'm out of sublime - Sorry guys !

**Comment by fritzmg** [comment]
Too bad, I seem to have the same problem - however I have no idea how to fix it. When running `FindKeyConflics` it shows me _a lot_ of "conflicting" key bindings. Are all these really the problem?

I only see one related to SublimeCodeIntel:
```
 [ctrl+shift+space]
   expand_selection                         Default               
   code_intel_auto_complete                 SublimeCodeIntel   
```
But I do not see how this could cause this issue. And even if: how do I change this key binding of SublimeCodeIntel? I can only add new user defined key bindings.

**Comment by balcsida** [comment]
I get the same error, finding key conflicts did not fix the issue for me.

While I understand that you switched to VSCode (I also use it every day), but could you please reopen this issue, @etiennejcharles, as this is still affecting some of us?

Thank you in advance! 🙂
