### ISSUE TITLE
SublimeCodeIntel did not work for python

### ISSUE THREAD

**Issue by onion5376** [SublimeCodeIntel/SublimeCodeIntel#404]
I write python scripts with sublime text3. After reading the readme file, I have added some extra libraries to the "config" file, and reopen the sublime text. But, sublime text did not pop up some hittings about the extra functions which I have added. I have reinstall the sublimecodeintel and sublime text, the problem still was not solved.

**Comment by Kronuz** [comment]
Is this still an issue in the latest version? If so, I'll investigate. It seems an encoding problem, perhaps a file with weird encoding?

**Comment by Kronuz** [comment]
@onion5376, this should be fixed since v2.1.0

**Comment by DoseMendoza** [comment]
Me da error al descomprimir el archivo
