### ISSUE TITLE
Pressing TAB in JS object inserts key: "value",

### ISSUE THREAD

**Issue by MightyPork** [SublimeCodeIntel/SublimeCodeIntel#415]
It's extremely annoying.

I like keys and values separated by some tabs, like this:

```
var panels = {
	do_refresh:		false,
	refresh_time:	-1,
	refresh_url:	null,
	viewport:		null, // viewport_vpt
	do_move:		false, // enable item dragging
	move_url:		null, // url to move ajax action
	item_class:		'item',
};
```

When I navigate behind the colon:

```
{
	myKey:| 'myValue',
}
```

Hit tab:

```
{
	myKeykey: "value", 'myValue',
}
```
Wtf just happened?

So I have to hold shift all the time, very annoying. I was looking for a similar fix like there is to the bug in PHP, where it inserted `<list>` in `array()`, but couldn't find anything. 

In tree_php.py, there is

```
php_ignored_calltip_expressions = ("if", "elseif","else",
                                       "for", "foreach",
                                       "while",
                                       "array", //<-- add this here
                                       "switch",
                                       )
```
and it works nice. There is nothing like that in tree_javascript.

**Comment by Kronuz** [comment]
Closing as invalid then.
