### ISSUE TITLE
SublimeCodeIntel does not load on Sublime Text 2 Windows 8.1

### ISSUE THREAD

**Issue by budara** [SublimeCodeIntel/SublimeCodeIntel#420]
I have successfully installed the SublimeCodeIntel from Package Control, but it does not load or show up on Preferences > Package Settings, though I can see the SublimeCodeIntel folder on browsing Packages folder. I also re-installed the package copying files directly from github, but not sign of loading. Checked the console on loading, no errors or nothing showing related to sublimecodeintel. Can anyone help, what's going on ? Did not find any topic related to this one. So, please help.

**Comment by Kronuz** [comment]
Yes, that happens. Please read the Tronleshooting section of the README. Also, full ST2 should be fixed in a more recent SublimeCodeIntel version.
