### ISSUE TITLE
Crashes ST3 every time User config is saved

### ISSUE THREAD

**Issue by johnathanz** [SublimeCodeIntel/SublimeCodeIntel#423]
Every time I save the user config (Settings -> User) for SublimeCodeIntel, it crashes ST3 (build 3065), running on Mac OSX Maverick.

By crash I mean: Mac Spinning Beach ball of death.  Only affects ST3 though and none of the other apps (thankfully!)

After forcing quit the ST3 app, the user config is actually saved.

Anyone else experiencing this?

**Comment by PixelT** [comment]
+1

**Comment by wizza-smile** [comment]
I fixed this issue in my fork of this project. Find it and lots of other improvements here:
https://github.com/wizza-smile/SublimeCodeIntel3

**Comment by yumitsu** [comment]
@wizza-smile it's amazing. Did you open a merge request?

**Comment by wizza-smile** [comment]
yes I did, some months ago. But I kind of changed my agenda. Should you find any bugs, please let me know!

**Comment by Kronuz** [comment]
Fixed in newer releases thanks to wizza-smile's pull request.
