### ISSUE TITLE
Need ability to configure db_base_dir

### ISSUE THREAD

**Issue by andig** [SublimeCodeIntel/SublimeCodeIntel#426]
The codeintel db on Windows lives in %userprofile%\.codeintel. In my case %userprofile% is backed up to a network share which is horribly slow with the zillions for files from the db. I'd like to mode the db (or the entire .codeintel folder) to a separate location, e.g. in /temp.

Any advise how to configure this?

**Comment by wizza-smile** [comment]
SublimeCodeIntel3 offers you the possibility to define a database dir per project in your *.sublime-project file. Let me know if its working for u!

https://github.com/wizza-smile/SublimeCodeIntel3

**Comment by Kronuz** [comment]
:+1: this is great! I've pulled the change to recent releases of SublimeCodeIntel. Thinking about it, now that it's mentioned, the .codeintel folder could be causing ST sluggishness if it's on a network drive.
