### ISSUE TITLE
Intellisense error on HTML

### ISSUE THREAD

**Issue by BrodaNoel** [SublimeCodeIntel/SublimeCodeIntel#434]
Hi guys.
I'm attaching 2 files to show you an error.
When I'm into a HTML file, and press ENTER after a div, the intellisense reccomend to me this option (see "error.png" file), and, if I press ENTER, I'll write this HTML (look "result.pn" file).

I was trying to write 2 new lines, or more, and that error is happening all time. I can't write 2 new lines because that.
Please, fix that guys. I can't install SublimeCodeIntel just because that.
![error](https://cloud.githubusercontent.com/assets/1837969/4924068/dc55cc1e-651f-11e4-80ba-0437d960e97f.png)
![result](https://cloud.githubusercontent.com/assets/1837969/4924069/dc618d06-651f-11e4-90fc-df7032d0d4e4.png)

**Comment by Kronuz** [comment]
is this still happening in the latest release v2.1.4? please re open the issue if so.
