### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by fiznool** [SublimeCodeIntel/SublimeCodeIntel#450]
Thanks for the work on a great plugin. I was wondering if there is still an active maintainer for the project?

If not, would you consider handling over the reins? There is at least one fork that I know of that fixes some of the issues currently in the tracker.

(I'd like to make it clear that I'm not interested in taking over - just putting out the question, as this is quite a popular plugin.)

**Comment by Kronuz** [comment]
I would certainly love to have help maintaining it, I'm still interested in updating it, tweaking it and improving it, but more help by some would be awesome. Ideally, the more people involved the better. Perhaps one maintainer per supported programming language, one per platform in charge of releases and one for upgrading the engine, with the help of a couple others fiddling with the code and fixing issues. Unfortunately there aren't any volunteers yet... ideas?

**Comment by adramalech** [comment]
Hey I would love to get started and contribute when I can.  Do you have a to-do list?  Is there a milestone list?  Is the issue tracker cleaned up?  Just want to get started fast as possible as I also use this plugin for my own projects.

**Comment by Kronuz** [comment]
We need to clean up the issues here in GitHub... it's full of old stuff and useless reports. I need help for that.
