### ISSUE TITLE
Javascript completing after semi-colon

### ISSUE THREAD

**Issue by peterorum** [SublimeCodeIntel/SublimeCodeIntel#461]
Hi,

Now at the end of a line (;), the auto-completer always pops up, and if I press enter as usual, I get `length` added. How can I stop auto-completion after a semi-colon?

Thanks,
Peter

**Comment by Kzinglzy** [comment]
i get the same problem on Python !!
It is really angry the auto-completer pops up after i press ':'
Help!
Thanks

**Comment by Kzinglzy** [comment]
maybe you could add this to your user setting

    {
        "codeintel_live": false
    }
it works for me.

**Comment by peterorum** [comment]
Thanks, @Kzinglzy . That stopped the auto-completion on semi-colon. I also had to change my manual completion key as ctrl+shift+space wasn't coming up with anything. (Don't know what else it's assigned to). It also only happened on 2 or my 3 projects, so perhaps there's something not parsing appropriately. I deleted the index, but it still happened after re-indexing. Anyway, I'll see how it goes now.

**Comment by Kronuz** [comment]
I can't reproduce this. Can you provide an example of code with this problem, please.

**Comment by peterorum** [comment]
![image](https://cloud.githubusercontent.com/assets/5625692/5873321/28a305a2-a349-11e4-96dc-3097313f8125.png)

This is from the project https://github.com/peterorum/random

Thanks,
Peter

**Comment by Kronuz** [comment]
Can you try with the newest release, please? I think this is fixed. Reopen if the problem is still there.

**Comment by peterorum** [comment]
![image](https://cloud.githubusercontent.com/assets/5625692/5895407/32faf9bc-a572-11e4-89bf-b88e786d7b68.png)

Hi,

I'm using v2.1.6, & deleted ~/.codeintel. But the issue remains.

Cheers,
Peter

**Comment by Kronuz** [comment]
Hm this seems to be native or fast trigger autocompletion a (SublimeCodeIntel autocomplete show the type; i.e. [function], [variable], [method]. I wonder why this is happening. In 2.1.6, fast trigger are not shown after stop characters and I believe semicolon is a stop character for JavaScript. Weird. Even worst, I can't make it fail here... even with that repo you mentioned.

**Comment by 66beta** [comment]
same issue with CSS

**Comment by waynedunkley** [comment]
I have this same issue currently

**Comment by tamiros** [comment]
I have the exact same problem with javascript on sublime3.
![image](https://cloud.githubusercontent.com/assets/6626234/9120511/b8f3ce62-3c4a-11e5-9998-6ad63056805c.png)

**Comment by mgmcdermott** [comment]
Same issue here, using v2.2.0+st3. Tried uninstalling, deleting cache, reinstalling, removing all user settings, and still pops up on semi-colon. Love the package but this makes it unusable for me.
<img width="371" alt="screen shot 2015-08-07 at 10 44 05 am" src="https://cloud.githubusercontent.com/assets/8161781/9138393/750db86e-3cf1-11e5-83db-b6a41a0b07b7.png">

**Comment by yduman** [comment]
Same issue here, using latest version on Sublime Text 3. After I press the semicolon it always pops up with some hints (see image). Anybody knows how to fix this ?
![image](https://cloud.githubusercontent.com/assets/11931774/10262700/6fe28c02-69d3-11e5-86d1-953817163e1b.JPG)

**Comment by waywaaard** [comment]
Same here -.-

**Comment by Minhui-Zh** [comment]
I got the same problem with yduman.

**Comment by lockz** [comment]
Same problem
![clipboard01](https://cloud.githubusercontent.com/assets/5790762/12343727/bbc810fe-bb79-11e5-8db2-3d2fe66b0a6e.jpg)

**Comment by catgsmith** [comment]
Here's a workaround : 
Select Package Settings > SublimeCodeIntel > Key Bindings - User, and add the following to the Default (OSX).sublime-keymap - User:
```
[
    { "keys": ["super+;"], "command": "insert", "args": {"characters": ";\n"} },
    { "keys": [";"], "command": "run_macro_file", "args": {"file": "Packages/User/unAutoSemiColon.sublime-macro"} }
]
```
Here is the file (OSX) Mac: Library>Application Support>Sublime Text 3>Packages>User>
save file unAutoSemiColon,sublime-macro:
```
[
	{
		"args":
		{
			"characters": ";"
		},
		"command": "insert"
	},
	{
		"args":
		{
			"by": "characters",
			"forward": false
		},
		"command": "move"
	},
	{
		"args":
		{
			"by": "characters",
			"forward": true
		},
		"command": "move"
	}
]
```

**Comment by richbon75** [comment]
thanks, @catgsmith - that solved the issue for me!

**Comment by anorudes** [comment]
Thanks, @catgsmith, nice idea

**Comment by Molunerfinn** [comment]
Thanks to @catgsmith ,I find a similiar way to solve this problem in Windows:
Select `Package Settings > SublimeCodeIntel > Key Bindings - User`, and add the following to the Default (Windows).sublime-keymap - User:
`{ "keys": [";"], "command": "run_macro_file", "args": {"file": "Packages/User/unAutoSemiColon.sublime-macro"} }`.
And then Select `Preferences -> Browser Packages`,save file unAutoSemiColon.sublime-macro:
```json
[
	{
		"args":
		{
			"characters": ";"
		},
		"command": "insert"
	}
]
```
Finnally, restart your sublime and the problem will be solved~

**Comment by Rishi321** [comment]
@Molunerfinn That works great, is there a way to modify it for any characters eg, for ":" and " " (space)
I cannot find anyway to pass an argument to the macro, or take the currently added character.
Thoughts..

**Comment by zachradtka** [comment]
I am using version 2.2.0 and still have the same problem as others. Any reason this issue is not re-opened?

The workaround is great, BTW!

**Comment by evaldeslacasa** [comment]
It worked for me as well on Windows, ### BUT adding the command in Preferences -> Package Settings -> SublimeCodeIntel -> Key Bindings - Default instead of -User.

**Comment by QinDynastyDragon** [comment]
@Molunerfinn @catgsmith , I've did exactly what you guys told me, but it turns out that 
{ "keys": [";"], "command": "run_macro_file", "args": {"file": "Packages/User/unAutoSemiColon.sublime-macro"} }
will prevent me from adding semicolon anywhere. I want the semicolon to be added, just without the autocomplete suggestions popping. Anyone could solve this?

**Comment by edyshor** [comment]
I had the same problem, a popup as soon as I typed a semicolon (see image), but I had installed a bunch of other packages, so, after I disabled "tern for sublime" the problem disappeared.

![popup after semicolon](https://user-images.githubusercontent.com/1146916/27269921-986669ac-54b2-11e7-8736-dd83f7820376.png)

**Comment by wanradt** [comment]
I am sure, that this problem involves "term for sublime", cause it appeared after installing it, but disabling term is not solution I am looking for. 

So "why" and "how" are still eligible questions, I think.

**Comment by sawyna** [comment]
@QinDynastyDragon have you seen if console gives any error when you try typing semicolon? I got the same error as you got. It was preventing me from entering semicolon. Turns out the file location path was not correct. Console clear says it's unable to read the macro. 

@wanradt I have tern_for_sublime as well running and the issue got resolved for me with the macro solution proposed above.

**Comment by SystemDisc** [comment]
Add this to your settings:
```json
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc - punctuation.terminator - punctuation.separator"
```
