### ISSUE TITLE
PHP not autocomplete function in `if( here )`

### ISSUE THREAD

**Issue by ptcong** [SublimeCodeIntel/SublimeCodeIntel#462]
I'm writing an if condition that check if a class is exists or not.
I typing `if(!class_e` then press CTRL + SPACE but have no suggestion for the case.
I tried with other functions in the `if` but result is same.

**Comment by alex-coder** [comment]
This problem is resolving now [in this issue](https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/459)
