### ISSUE TITLE
unresponsive after last updates

### ISSUE THREAD

**Issue by mirkhamidov** [SublimeCodeIntel/SublimeCodeIntel#465]
I get this message after every start Sublime 2.
 ![2015-01-21_13-23-27](https://cloud.githubusercontent.com/assets/2736223/5834710/84d738b8-a171-11e4-80b6-fc5e331ffe2d.png)

What I have to do?

**Comment by rassom** [comment]
+1 
I also get the message (and it Sublime really does become unresponsive with latest SublimeCodeIntel installed).

**Comment by mirkhamidov** [comment]
same with #460
