### ISSUE TITLE
PHP slowest triggers for autocomplete after 2.1.4

### ISSUE THREAD

**Issue by xskif** [SublimeCodeIntel/SublimeCodeIntel#467]
ST3 Ubuntu 14.04.1

When i try to type class method like before: `fun+[tab]` it complete like `function` not like before:
```php
public function FunctionName($value='')
{
    # code...
}
```

but if i wait for a second, tooltip offers me the right snippet

Before  2.1.4 update `fun+[tab]` complete the language or situation oriented snippet, like lambda functions, callbacks, class methods, etc. Now it's just a `function` word.

**Comment by xskif** [comment]
Just noticed that all php triggers become slowest, type `count+[tab]` for autocomplete `count()` function and it's just type `[tab]` symbol, but if i wait a second, editor offers me tooltip with `count()` function, only after that i can press `[tab]` for correct completion.

**Comment by Kronuz** [comment]
How can I test this? I don't use PHP, so I'd need some files for a testing environment. It'd be useful to have "testing" repositories for each language with code in them and comments as to test what is expected and be able to see when and how slow completions happen.

**Comment by xskif** [comment]
I think trigger must firing async when i typing 3-more symbols, but not a second later after i stops.

**Comment by xskif** [comment]
@Kronuz 
`How can I test this?`
- you can just create php file and create class, then methods inside, and then just few built-in php functions.

php+tab
class+tab
fun+tab - must work as above
count+tab / substr+tab / etc...

php looks like python, c++ and pearl, it's easy to test for you

**Comment by xskif** [comment]
maybe @wizza-smile can help you

**Comment by xskif** [comment]
maybe after 2.1.4 `[tab]` press didn't try to autocomplete if trigger not firing? maybe `[tab]` should firing trigger manualy as `ctrl+shift+space` ?

**Comment by wizza-smile** [comment]
this is working in **SublimeCodeIntel3**!

**Comment by xskif** [comment]
@wizza-smile , can you upload SublimeCodeIntel3 in PackageControll ? Or maybe you can pull-request fix here ? It's realy more comfortable to use autoupdate by package plugin instead of using git every time, and watching for new versions and fixes.

**Comment by wizza-smile** [comment]
@xskif , I desperately need some Users who are willing to give me feedback for **SublimeCodeIntel3**, in order to keep pushing development of Sublime autocompletion plugins. So please, take the badge and help me by installing it and opening issues on my repo.

> that was working on origin SublimeCodeIntel before last update to.
And you are always free to downgrade!

**Comment by xskif** [comment]
@wizza-smile i need to uninstall original plugin to install your fork ?

**Comment by wizza-smile** [comment]
you to add "SublimeCodeIntel" to ignored packages and install fork in a folder "SublimeCodeIntel3"!

**Comment by xskif** [comment]
got it.
