### ISSUE TITLE
CodeIntel pops up even though "live" is set to false

### ISSUE THREAD

**Issue by minitauros** [SublimeCodeIntel/SublimeCodeIntel#474]
I have "live" set to false, but nonetheless the SublimeCodeIntel popup pops up every time I start typing something that it can autocomplete. I have tried reinstalling but it doesn't seem to work. Anything else I can do to try and fix it?

**Comment by Kronuz** [comment]
Are you positively sure the popup is from SublimeCodeIntel and not from the native autocomplete from Sublime Text? SublimeCodeIntel auto completed elements show "*[function]*" or "*[variable]*" or "*[method]*" in front of them in the autocomplete list.

If so, what version of Sublime are you using, what version of SublimeCodeIntel and what language are you working with? And where and how exactly did you set "live" to false?

**Comment by minitauros** [comment]
Well, in my Preferences.sublime-settings I have these lines:

	"auto_close_tags": false,
	"auto_complete": false,
	"auto_match_enabled": false,

and in my SublimeCodeIntel.sublime-settings I have these lines:

"sublime_auto_complete": false,
	"codeintel_live": false

and this is what it looks like:

![imag1131](https://cloud.githubusercontent.com/assets/3321372/5959033/ea188d44-a7ca-11e4-80b0-5f68be39d97c.jpg)

**Comment by louisl** [comment]
I'm suffering the same problem, the pop up is appearing instantly every time I type something.

**Comment by wizza-smile** [comment]
you have probably set your `"codeintel_live": false` in a wrong position!

**Comment by vhoen** [comment]
I have the same problem.
I use sublime3 linux to code in PHP and the autocomplete keeps popping up whenever I type something.
I put the following settings in SublimeCodeIntel.sublime-settings : 
"auto_complete": false,
"auto_close_tags": false,
"auto_match_enabled": false,
"sublime_auto_complete": false,
"codeintel": false,
"codeintel_live": false,

I might have set "codeintel_live": false in the wrong place, and I would be interested to know where to set it.

Thanks in advance.

**Comment by wizza-smile** [comment]
``` 
"auto_complete": false,
"auto_close_tags": false,
"auto_match_enabled": false,
```

These are Sublime settings they are out of place in SublimeCodeIntel.sublime-settings

`"sublime_auto_complete": false,` this one was dropped, it doesn't exist anymore!

```
"codeintel": false,
"codeintel_live": 
``` 
This is correct but it's hard to tell whether you made a mistake, if you don't post your whole SublimeCodeIntel.sublime-settings!

**Comment by minitauros** [comment]
Those first three ARE in my regular Sublime preferences file :). But, since you ask, my whole settings file looks like (I didn't want to bother you with the whole file if not necessary):

{
	"atomic_save": false,
	"auto_close_tags": false,
	"auto_complete": false,
	"auto_match_enabled": false,
	"color_scheme": "Packages/User/Twilight (SL).tmTheme",
	"detect_indentation": false,
	"font_size": 10,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage",
		"BracketHighlighter",
		"Trimmer",
		"HighlightWords",
		"AlignTab",
		"RegReplace",
		"SublimeCodeIntel"
	],
	"rulers":
	[
		80,
		120
	],
	"scroll_speed": 0,
	"shift_tab_unindent": true,
	"tab_size": 4,
	"translate_tabs_to_spaces": false,
	"word_wrap": false
}

And my code intel settings file:

{
	// "sublime_auto_complete": false,
	"codeintel_live": false
}

**Comment by vhoen** [comment]
Per your suggestion I removed sublime settings. Here is my code intel settings : 

{
    "codeintel": false,
    "codeintel_live": false
}

The completion keeps popping up (I restarted sublime), is there something I am missing ?

**Comment by wizza-smile** [comment]
Your settings are correct. What you are seeing will be your default Sublime completions. This is a bug that has been fixed in `CodeComplice`. It's a fork of this plugin and available via package-control.

**Comment by vhoen** [comment]
Indeed, I don't have the bug when using code complice instead of sublime code intel.

**Comment by minitauros** [comment]
So SublimeCodeIntel is somehow triggering my Sublime's autocomplete functionality? :o

**Comment by charlesroper** [comment]
Same problem here but with a twist. I'm trying to disable the live popup only in certain syntaxes, but the  `codeintel_live_disabled_languages` setting seems to be getting ignored. I've tried CodeComplice too. Here's my settings:

```json
{
  "codeintel_live": true,
  "codeintel_live_disabled_languages": ["Markdown", "MultiMarkdown", "md", "text.html.markdown", "HTML"]
}
```

That should disable the live pop-up in Markdown and HTML, right? But it doesn't. If I set `"codeintel_live": true` to `false` in CodeComplice, then the pop-up is globally disabled. However, in SublimeCodeIntel, even this setting apparently does nothing as others in this thread have found. Even setting `"codeintel": false` doesn't seem to work in SublimeCodeIntel.

**Comment by spectacles** [comment]
@charlesroper please open an issue at https://github.com/spectacles/CodeComplice and you shall receive help  ;)

**Comment by Kronuz** [comment]
@minitauros that autocomplete isn't from SublimeCodeIntel, it's from native Sublime Text autocompletion. It happens even with a vanilla Sublime Text for me. I'm not sure then...

**Comment by minitauros** [comment]
Well, that could be, but when I disable SublimeCodeIntel the popup doesn't pop up. However, when I have SCI enabled, it does.

**Comment by wizza-smile** [comment]
@minitauros mmh, as I said, it's a bug. It's not behaving as expexcted!

**Comment by peterorum** [comment]
I also found codeintel was ignoring the live option suddenly in 2.1.7. I was using that to avoid the stop issue in javascript which is still happening. But now that cannot be avoided even by setting live to false. I had to uninstall codeintel.

**Comment by wizza-smile** [comment]
> So SublimeCodeIntel is somehow triggering my Sublime's autocomplete functionality? :o

@minitauros the mechanism has various dimensions. I will try to explain that a bit. There is only one auto-complete completions-popup in sublime, so **yes** SublimeCodeIntel (or any other plugin or Sublime itself) can trigger that autocomplete functionality. Once it gets triggered every plugin (and sublime itself has a lot of plugins shipped with it) gets the chance to add its completions to the mix. This is what the function `on_query_completions` is for.

Then there is the possibility to deny Sublime to add its completions to the mix, this can be done in two different ways and this is where things get a bit complicated.

If you are interested in the topic, you might consider studying the source code of SublimeCodeIntel.py!

Take care!

**Comment by wizza-smile** [comment]
@peterorum I invite you to install CodeComplice via packageControl. It's available for SublimeText 2 and 3. The `codeintel_live` setting is surely working there and I'd be interested to investigate the other issue (completions after `;`) with you! Thanx for reading!

**Comment by peterorum** [comment]
Thx @wizza-smile .  I did try CodeComplice a few days ago, and found it still had the completions issue. I think I think I'll back check in a month & then I'll have more time to pursue it.

**Comment by wizza-smile** [comment]
@peterorum CodeCompice will help will only give you the option to set `codeintel_live` to false. The other issue will be somewhere in your settings/other plugins, not in SublimeCodeIntel. Open an issue at CodeComplice any time and I will do my best to figure out, what exactly is happening to you!

**Comment by wizza-smile** [comment]
@peterorum I am confident to have fixed your whole issue in the latest version CodeComplice. Would be great if you could check it out and feedback!

**Comment by peterorum** [comment]
@wizza-smile Thanks. I noticed I had AutocompleteJs installed, so I deleted it and so far CodeIntel has been working ok. If I find I'm missing anything or something else arises, I'll try CodeComplice again.

**Comment by ghvaldez** [comment]
Using version 2.1.7 with sublime text 3 on a Ubuntu.  I to am seeing this issue.  Coding language PHP but I don't think that matters.  Here are my relevant settings

 /* Disable Sublime Text autocomplete: */
    "sublime_auto_complete": true,
    /*
        Sets the mode in which SublimeCodeIntel's live autocomplete runs:

        true - Autocomplete popups as you type (the default).
        false - Autocomplete popups only when you request it.
    */
    "codeintel_live": false,

**Comment by Bandydan** [comment]
Suffering the same issue. Are there any changes done on this?

**Comment by wizza-smile** [comment]
remove SublimeCodeIntel and install CodeComplice! https://github.com/spectacles/CodeComplice

**Comment by ghvaldez** [comment]
I did and that did not solve my problem on Ubuntu 14.10

**Comment by wizza-smile** [comment]
'm sorry for you @ghvaldez! The problem will be your settings though, not your OS!

**Comment by setivolkylany** [comment]
The problem still live:

Sublime Text settings:

> "auto_close_tags": false,
> "auto_complete": false,
> "auto_match_enabled": false
> 

SublimeCodeIntel's settings:

> {
>     "codeintel": false,
>     "codeintel_live": false,
>     "sublime_auto_complete": true
> }

**Details**:

> wlysenko-Aspire project # subl --version
> Sublime Text Build 3126

Version the SublimeCodeIntel is 2.2.0 + st3
