### ISSUE TITLE
colon bug on the Python code

### ISSUE THREAD

**Issue by Kzinglzy** [SublimeCodeIntel/SublimeCodeIntel#480]
When i am defining a function, after I write the `:` ,  the SublimeCodeIntel showed me the suggestion `abs`, for example

    def hello():

and when I press the enter to goto next line, i will get the `abs` after the `:`, just like
    
    def hello():abs

Actually, I had added the  `"codeintel_live": false` to my user setting and reinstalled or deleted the cache lots of time.  But it still not work.

Help, please.

**Thanks.**

**Comment by spectacles** [comment]
Remove SublimeCodeIntel and install CodeComplice from package control. It's a fork of this project and has this and lots of other things working!!

**Comment by Kzinglzy** [comment]
Actuallly, there is a conflict between anaconda and SublimeCodeIntel, when I remove anaconda, the issue gone.
