### ISSUE TITLE
Implement new Tooltip

### ISSUE THREAD

**Issue by iamntz** [SublimeCodeIntel/SublimeCodeIntel#483]
Hi guys! Glad to see the project got some traction again!

Jon just released a new version of ST beta that implements... **TOOLTIPS!**

http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583

Maybe you update the plugin to use this new feature ;)

Thanks!

**Comment by Kronuz** [comment]
Absolutely! This is what we all have been waiting for! :D

I'm also working in a new version of the plugin, which features a lot of stability and performance fixes. The core of the completion engine is being separated from the plugin and will probably need to be installed using pip (Python's package manager), then it'll run as an out of process (so it doesn't/never eats all the Sublime Text resources)

**Comment by iamntz** [comment]
:+1: 

If you're working on a new version, please consider #323 as well. Thanks!

**Comment by rmccue** [comment]
Implemented over in spectacles/CodeComplice#29 :)

**Comment by Kronuz** [comment]
It's also implemented in 3.0.0 (still alpha), soon to be released, along with many improvements.
