### ISSUE TITLE
Can not install SublimeCodeIntel through Package Control

### ISSUE THREAD

**Issue by kmargaritis** [SublimeCodeIntel/SublimeCodeIntel#493]
I don't know if this is related with the recent release but SublimeCodeIntel is not available on Package Control

Package Control message:
```
The package specified, SublimeCodeIntel, is not available
```

The same happens if you try to search SublimeCodeIntel from Package Control web interface

**Comment by ThomasBormans** [comment]
+1

**Comment by neokore** [comment]
+1

**Comment by FabianMeul** [comment]
+1

**Comment by edigu** [comment]
+1 on ST3
Platform: OS X 10.9.5

**Comment by Kronuz** [comment]
I updated the package to have version 2.1.8 and version 3.0.0 alpha, I don't know how it got "removed", I'm still checking...

**Comment by kmargaritis** [comment]
thanks @Kronuz !

**Comment by Kronuz** [comment]
Should be working now... v3.0 alpha screwed things up, sorry.

**Comment by kmargaritis** [comment]
:+1:

**Comment by maxedison** [comment]
I'm still not able to find it via package control.
