### ISSUE TITLE
Cannot install CodeIntel on OS X 10.8

### ISSUE THREAD

**Issue by rk** [SublimeCodeIntel/SublimeCodeIntel#499]
I'm not a python developer, so I've no experience with the language or its environment. So I'm starting from a stock install of Python 2.7.2 on OS X 10.8. I installed pip using easy install without issue.

Installing CodeIntel fails when compiling the subprocess32 dependency:

```text
Collecting subprocess32
  Using cached subprocess32-3.2.6.tar.gz
Installing collected packages: subprocess32
  Running setup.py install for subprocess32
    building '_posixsubprocess' extension
    clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _posixsubprocess.c -o build/temp.macosx-10.8-intel-2.7/_posixsubprocess.o
    clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
    clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
    error: command 'clang' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/_b/k8bk3bv521n3w7rd9c3r3xn40000gn/T/pip-build-Anao35/subprocess32/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_b/k8bk3bv521n3w7rd9c3r3xn40000gn/T/pip-aAhKpn-record/install-record.txt --single-version-externally-managed --compile --user:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib.macosx-10.8-intel-2.7
    
    copying subprocess32.py -> build/lib.macosx-10.8-intel-2.7
    
    running build_ext
    
    building '_posixsubprocess' extension
    
    creating build/temp.macosx-10.8-intel-2.7
    
    clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _posixsubprocess.c -o build/temp.macosx-10.8-intel-2.7/_posixsubprocess.o
    
    clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
    
    clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
    
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/_b/k8bk3bv521n3w7rd9c3r3xn40000gn/T/pip-build-Anao35/subprocess32/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_b/k8bk3bv521n3w7rd9c3r3xn40000gn/T/pip-aAhKpn-record/install-record.txt --single-version-externally-managed --compile --user" failed with error code 1 in /private/var/folders/_b/k8bk3bv521n3w7rd9c3r3xn40000gn/T/pip-build-Anao35/subprocess32
```

I tried looking for the `install-record.txt` file but it appears to be deleted when the install fails.

I guess that the compile command being passed to XCode is for either an older or a newer version of XCode. Because I'm on 10.8 the latest version of XCode is "incompatible" with my OS.

**Comment by Kronuz** [comment]
This is a known problem in Mavericks. Please try installing as: ``sudo ARCHFLAGS="-arch x86_64" CFLAGS=-Wunused-command-line-argument-hard-error-in-future pip install -U codeintel``

While at it, we need wheels built for every platform we can, having Mavericks wheels would help. If the above command success, would you mind re-building as a wheel? You'll need the https://pypi.python.org/packages/source/C/CodeIntel/CodeIntel-0.1.6.tar.gz file in PyPI, the wheel package (`pip install wheel`). Untar the file and run `python setup.py bdist_wheel` then share the `dust/*.whl` file. We'll need someone who can do this process for every release, on every platform, if you are interested in collaborating.

**Comment by rk** [comment]
Well, that command lets me install the package on Snow Leopard.

I'd like to help, but it's complicated. I don't know python at all—I can read the code and get the gist most the time. But when it comes to understanding how to set up a binary release and contribute, I'm kinda lost. On top of that is the fact I'll only be able to contribute on my free-time here at work. So I wouldn't be able to guarantee when I could send you the wheel file during the day/week if we're slammed.

I'd like to help, but I can't guarantee my availability or experience in python.

Also, we're planning to upgrade to OS X 10.10 sometime this year. Probably during summer.
