### ISSUE TITLE
Cannot install CodeIntel on OS X 10.9.5 using pip

### ISSUE THREAD

**Issue by sCreami** [SublimeCodeIntel/SublimeCodeIntel#501]
Following today's message on CodeIntel 3.0. I did try to install CodeIntel using pip but I'm having difficulties building it. I'm not a python coder so I don't understand what it means.
I'm linking the log below. It's quite huge so I posted it on pastebin
http://pastebin.com/mPTfRELe

**Comment by Kronuz** [comment]
That basically just says you need to have libpcre installed (`brew install pcre`)... but don't worry too much for now, this package is still not needed for the current SublimeCodeIntel and we are working and refining the building process. We'll most likely distribute already compiled binary files or clear and easy instructions for building it when SublimeCodeIntel v3.0 is released.

**Comment by sCreami** [comment]
Thank you for that quick reply. That log made me really uncomfortable so I'll probably wait for the compiled binary files.
