### ISSUE TITLE
PHP class properties in v3

### ISSUE THREAD

**Issue by daltones** [SublimeCodeIntel/SublimeCodeIntel#508]
There's an issue about autocompletion of PHP class properties in v3 (oop).

When you have this:

```php
class SomeClass
{
    private $fooProperty;

    public function barMethod()
    {
        $this->AUTO_COMPLETE_HERE
    }
}
```

Suggestions at that point are ```$fooProperty  (Variable)``` and ```barMethod   (Function)```. And then, if you go forward on ```$fooProperty```, it autocompletes to ```$this->$fooProperty``` (wrong PHP syntax). It should autocomplete to ```$this->fooProperty```, like v2 correctly did.

This wrong autocompletion affects all related to object instances, not only ```$this```.

Btw, there's some other issues… But SublimeCodeIntel is really faster with codeintel oop. Great job! ;)

**Comment by Kronuz** [comment]
Oh, I see! Thanks for reporting. It'd be great if each problem report had such example for me to easily reproduce the issue. I'll try to fix this.
