### ISSUE TITLE
 A plugin (SublimeCodeIntel) may be making Sublime Text unresponsive by taking too long (0.020000s) in its on_modified callback.

### ISSUE THREAD

**Issue by thomaspha** [SublimeCodeIntel/SublimeCodeIntel#513]
Hi,There. When i start sublime text 2 on win7. its popup a window display" error: A plugin (SublimeCodeIntel) may be making Sublime Text unresponsive by taking too long (0.020000s) in its on_modified callback.This message can be disabled via the detect_slow_plugins setting" I did the operation as the link(https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/460)  -> (https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/README.rst.) said ..but the problem still exist. Dose anyone know how to resolve the problem. The popup window  annoyed.

The following items is the control logs:
startup, version: 2221 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 2/sublime_text.exe
working dir: /C/Users/Administrator/Desktop
packages path: /C/Users/Administrator/AppData/Roaming/Sublime Text 2/Packages
settings path: /C/Users/Administrator/AppData/Roaming/Sublime Text 2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text.exe
Py_GetExecPrefix(): C:\Program Files\Sublime Text 2
Py_GetProgramFullPath(): C:\Program Files\Sublime Text 2\sublime_text.exe
Py_GetPath(): C:\Program Files\Sublime Text 2\python26.zip;C:\Program Files\Sublime Text 2\DLLs;C:\Program Files\Sublime Text 2\lib;C:\Program Files\Sublime Text 2\lib\plat-win;C:\Program Files\Sublime Text 2\lib\lib-tk;C:\Program Files\Sublime Text 2
Py_GetPythonHome(): C:\Program Files\Sublime Text 2
catalogue loaded
found 12 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 8 files for base name Main.sublime-menu
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\01-ssl-windows.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\01-ssl-windows.py", line 1, in <module>
    from package_control import sys_path
ImportError: No module named package_control
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\02-bz2.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\02-bz2.py", line 2, in <module>
    from package_control import sys_path
ImportError: No module named package_control
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\0_package_control_loader\02-select-windows.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\02-select-windows.py", line 1, in <module>
    from package_control import sys_path
ImportError: No module named package_control
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\AdvancedNewFile\AdvancedNewFile.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\CSS\css_completions.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\comment.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\copy_path.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\delete_word.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\detect_indentation.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\duplicate_line.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\echo.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\exec.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\fold.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\font.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\goto_line.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\indentation.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\kill_ring.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\mark.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\new_templates.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\open_file_settings.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\open_in_browser.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\paragraph.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\save_on_focus_lost.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\scroll.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\set_unsaved_view_name.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\side_bar.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\sort.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\swap_line.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\switch_file.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\transform.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\transpose.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Default\trim_trailing_white_space.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Diff\diff.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\DocBlockr__init__.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\DocBlockr\jsdocs.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Emmet\emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\HTML\encode_html_entities.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\HTML\html_completions.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\HTMLBeautify\HTMLBeautify.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Insert Callback\Callback.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JsFormat\js_formatter.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Package Control\Package Control.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\Package Control\bootstrap.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\SublimeCodeIntel.py
Reloading plugin C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\ordereddict.py
plugin init time: 0.291633
loading bindings
loading pointer bindings
found 1 files for base name Spacegray Eighties.sublime-theme
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\Blob\Description-blob.sublime-completions:20:2
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\Event\Description-event.sublime-completions:50:3
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\File\Description-file.sublime-completions:48:2
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\Range\Description-range.sublime-completions:102:3
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\Style CSS\Description-style-css.sublime-completions:54:3
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\Text\Description-text.sublime-completions:18:3
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\TreeWalker\Description-treewalker.sublime-completions:50:3
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\URL\Description-url.sublime-completions:66:3
Error loading completion: Error trying to parse file: Trailing comma before closing bracket in C:\Users\Administrator\AppData\Roaming\Sublime Text 2\Packages\JavaScript Completions\JavaScript Completions\DOM\Worker\Description-worker.sublime-completions:26:3
Errors parsing theme:
Unknown attribute value
theme loaded
app ready
pre session restore time: 0.43099
startup cache, total files: 132 cache hits: 132
startup time: 0.595042 (package setup was not run)
loaded 1122 snippets
Package Control: Skipping automatic upgrade, last run at 2015-05-16 10:00:43, next run at 2015-05-16 11:00:43 or after
Writing file /C/Users/Administrator/Desktop/test.css with encoding UTF-8
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED False
WINDOW COMMAND ENABLED False
error: A plugin (SublimeCodeIntel) may be making Sublime Text unresponsive by taking too long (0.020000s) in its on_modified callback.

This message can be disabled via the detect_slow_plugins setting

**Comment by broonage** [comment]
I'm getting this too

**Comment by techalchemy** [comment]
Same here

**Comment by mohammad6006** [comment]
me too

**Comment by inreality** [comment]
I got the same problem
