### ISSUE TITLE
Just Asking: how hard would be to port codeintel to Atom?

### ISSUE THREAD

**Issue by hugochinchilla** [SublimeCodeIntel/SublimeCodeIntel#526]
I've been trying Atom for a couple of days now and I think it's ready enought for me to make the switch, the only one thing preventing me to do so is the inexistence of a similar plugin like this for Atom.

@Kronuz you know the project better than anyone, could you give an estimate of how much work would need to be done? Or may be, would you be interested in accepting money for doing so?

**Comment by Kronuz** [comment]
The newest version of SublimeCodeIntel (still beta) uses CodeIntel Python Package (https://pypi.python.org/pypi/CodeIntel)... the heavy lifting is done by that package.

If we can run command line commands from Atom (i.e. running the `codeintel` command from there) it should be very feasible to make it work... Noting the requirement of having to have Python 2 and the CodeIntel Python package also installed.

**Comment by hugochinchilla** [comment]
That's good to hear, today it's hackday, I will try to do something with it.

**Comment by Kronuz** [comment]
Installing newest (v3.0 aka oop) SublimeCodeIntel:
http://kronuz.io/using-sublimecodeintel-v30.html (in case you need a reference)

**Comment by hugochinchilla** [comment]
Thanks, I was looking at the code from the development branch, now I see I had to look at the oop branch, am I correct? 

Do you have any document which explains how to talk with the codeintel process once is up and running, a command list or protocol description? I thought it was going to be easier to reverse engineer the plugin

**Comment by hugochinchilla** [comment]
Me after 2 hours spelunking in the codeintel code

![Me](http://i.imgur.com/glt2D7O.jpg)

**Comment by Kronuz** [comment]
Yes, the oop branch is the one you want, you also need to instal CodeIntel Python package.

Regarding documentation, it uses Komodo oop protocol: https://github.com/Komodo/KomodoEdit/wiki/290-CodeIntel-OOP-Protocol ; however, it'd be probably recomeded to translate codeIntel.py in the oop branch (which contains the abstraction) and it's essentially the client library that launches and connects with the oop process (started by the the `codeintel` command installed by the Python package), and then create the plugin that uses that library (equivalent to `SublimeCodeIntel.py`)

**Comment by hugochinchilla** [comment]
Thank's a lot this helps me to undesrtand what the code is doing.

**Comment by cweagans** [comment]
FYI, https://github.com/Valloric/ycmd/pull/120 adds codeintel support to ycmd, so it might be easier to just integrate with YCMD. This gives you completion for a *lot* of languages.

**Comment by jeteon** [comment]
@hugochinchilla, I've been steeped in the CodeIntel source for a few months now and I can tell you a lot of it is still a mystery. A lot of this is because the documentation is pretty sparse and some of it isn't even in the public domain (https://github.com/Komodo/KomodoEdit/issues/201). @Kronuz's efforts have been invaluable in making it possible to use the engine outside of KomodoEdit however.

https://github.com/Valloric/ycmd/pull/120 is currently geared mainly at PHP support but the API of YCMD is much friendlier IMHO so if you can, I'd say YCMD integration is a good way to go, as @cweagans mentioned.

**Comment by hugochinchilla** [comment]
@cweagans  @jeteon  thanks for noticing this to me, I've subscribed to the issue and will follow the progress with great interest, I can test in on a large PHP project and give some feedback if needed as well.

**Comment by cweagans** [comment]
That would be very nice :)

**Comment by xskif** [comment]
Hi there. Any progress ?

**Comment by jeteon** [comment]
Most of the basic functionality of the PR is complete. There are mostly just architectural changes remaining. It hasn't been merged yet though.

**Comment by xskif** [comment]
@jeteon , will it be the independent plugin, or just the PR?

**Comment by xskif** [comment]
@jeteon , if you need any help to port codeintel functionality into the Atom plugin, i can try.

**Comment by jeteon** [comment]
The PR is for `ycmd`. The suggestion earlier in the thread is to use `ycmd` as an intermediary for integrating CodeIntel functionality into Atom. Have you worked with the CodeIntel code base before?

**Comment by xskif** [comment]
@jeteon , no, i haven't. But i'm worked with js/cs (required to make plugins).

**Comment by jeteon** [comment]
Have you seen the code for the YCMD Atom client? https://atom.io/packages/you-complete-me

**Comment by xskif** [comment]
@jeteon , no, i haven't seen it yet. I didn't even know about this package =)

**Comment by minj** [comment]
I got to say the documentation to set that package up is lacking....
Not even proper error handling, had to debug atom to find that server returns HTTP500 with `No semantic completer exists for filetypes: [u'js']`

Tsk tsk ;)
