### ISSUE TITLE
pip install codeintel fails

### ISSUE THREAD

**Issue by daltones** [SublimeCodeIntel/SublimeCodeIntel#552]
Hello! First of all, thanks for the last updates. =)

I need to ask: which OS are you testing codeintel installation via pip?

I use a GNU/Linux-based and last versions (include 0.9.3) fail on `pip install -U codeintel`. The error occours when the file “silvercity/PySilverCity/Src/PyLexerModule.cxx” couldn't be found.

So I downloaded the sources and realized that the directory “silvercity” is named in CamelCase (“SilverCity”). I just renamed it and installed manually without problems.

I guess everyone using a case-sensitive filesystem is not making it…

**Comment by mikk150** [comment]
I renamed the directory, it's actually easier

**Comment by igittGit** [comment]
what location did you copy the source directory to?

**Comment by mikk150** [comment]
download codeintel, unpack it rename silvercity directory, repack it, pip install it

**Comment by daltones** [comment]
Yeah, of course. That’s what I did.

My point is to fix the direct installation via ```pip install codeintel```.

**Comment by mikk150** [comment]
agreed!

**Comment by igittGit** [comment]
worked, thanks!

**Comment by Kronuz** [comment]
Should be fixed in 0.10.1, it has also been updated with Komodo codebase

**Comment by daltones** [comment]
@Kronuz macosx only? 😢

**Comment by Kronuz** [comment]
I've added wheels for linux, windows and mac... "should" be working, but I haven't really tried it. Please report back any findings! :)

**Comment by jaszhix** [comment]
I'm not able to install this using pip on Ubuntu 16.04 with almost all common build tools installed.

[Log](https://0bin.net/paste/nWl+jmDDQOk4VBfR#IMzX6cmU1wU8Ex0YECXSQMykKoFYt+LBwtjAd3JMpwQ)

**Comment by mikk150** [comment]
@jaszhix [try this](https://github.com/mikk150/st3-config/blob/master/install_codeintel.sh)

**Comment by jaszhix** [comment]
That worked, thanks!

**Comment by Kronuz** [comment]
There has been a lot of work going on with next version of CodeIntel and SublimeCodeIntel.

You should try installing new CodeIntel v2.0.0-beta.28 using: `pip install -U --pre CodeIntel` and SublimeCodeIntel should be in v3.0.0-beta.27

Both have undergone extensive refactoring and improvements.

**Comment by mikk150** [comment]
@Kronuz pip Codeintel does not work under ubuntu.....
