### ISSUE TITLE
Not working with windows sublime3 ??

### ISSUE THREAD

**Issue by getmonyinfo** [SublimeCodeIntel/SublimeCodeIntel#597]
I jsut  follow the install step. but it seems not working well
like:
var list = document.q
I want to show a list of  function like :querySelecto, querySelectorAll ...
but it show nothing ??

**Comment by sundaycrafts** [comment]
It not working too.
But `document.getElementsByTagName('')` for example is shown.

**Comment by nikklass** [comment]
This repo looks dead

**Comment by Kronuz** [comment]
Everything is heppening in other repository; in Kronuz/SublimeCodeIntel and Kronuz/CodeIntel
