### ISSUE TITLE
[ST3, SublimeCodeIntel 3.0.0-beta6] Missing functionality to manually trigger autocomplete

### ISSUE THREAD

**Issue by adnedelcu** [SublimeCodeIntel/SublimeCodeIntel#612]
Hi,

As the title of the issue says, the functionality to manually trigger autocomplete is missing.
In **SublimeCodeIntel v2** you had the command **code_intel_auto_complete** which could have been triggered when you pressed the default key mapping **Ctrl+Shift+Space**.

That command is missing now in the new **SublimeCodeIntel v3** and I haven't figured out how you can trigger the autocomplete through shortcut keys.
The only way I figured I could trigger it is through deleting the symbol that would normally trigger the autocomplete (e.g. "(", ".", ">") and input it again.
While doing that is a solution to the problem, I think it would be nice to have the command back.

**Comment by adnedelcu** [comment]
Created pull request #613.

**Comment by Kronuz** [comment]
It's really weird the class wasn't there. There was the default key map set up and all... thank you for adding it!

Anyway, by the way, how is v3 (oop) working for you?

**Comment by adnedelcu** [comment]
I have some problems with Sublime Text that is consuming lots of resources but I don't know if v3 is to blame or the SublimeLinter package that I added at the same time.

Other than that, v3 gives faster autocomplete and more precise than v2.
I've been using it for a week now.

**Comment by Kronuz** [comment]
Are the resources consumed from Sublime Text process? The heavy lifting of SublimeCodeIntel is done by the out of process CodeIntel command.

Please I beg you and encourage you to try figuring out if it is SublimeLinter or SublimeCodeIntel.

By the way, what operating system are you using?

**Comment by adnedelcu** [comment]
I don't know exactly which process uses the resources since at the time I figure out that the resources are consumed, the computer is not responsive and I need to force restart it.

I'm using Ubuntu 16.04.1. I had some problems installing the codeintel python package, because of the SilverCity vs silvercity problem, but the issue #552 helped me to fix that.

**Comment by adnedelcu** [comment]
I managed to find out what package was the resource hog. It was SublimeLinter.
I'm using it in a PHP project and sometimes the PHP process that it starts is not finished and keeps doing something, using resources until killed.

While trying to find out what package was the resource hog, I also found a "problem" with v3 (oop): the autocomplete is not working unless the previous character is a trigger character, as stated in the first message of this issue.

For example, if I write something like `$this->get` and then trigger the autocomplete, then nothing happens.
If instead I put the caret after > and then trigger the autocomplete, then the popup is displayed.

Any idea why this behavior?

**Comment by Kronuz** [comment]
Oh, yes! There is another function for that, which we should use there instead. I'll have to look it up.

**Comment by adnedelcu** [comment]
Is there a documentation for codeintel command? I can't seem to find one.

**Comment by Kronuz** [comment]
Should be fixed in v3.0.0-beta7
