### ISSUE TITLE
Can't download codeintel from package control

### ISSUE THREAD

**Issue by bws35** [SublimeCodeIntel/SublimeCodeIntel#641]
Can't find sublimecodeintel in package control anymore.
Tried to install it manually but it's still not working.

I'm getting an error:
ImportError: No module named 'six'.

**Comment by Kronuz** [comment]
We are currently experiencing some trouble with Package Control. Hopefully this will soon be fixed. Master branch now points to v3.0.0-beta; which still has issues with Windows. That too will soon be fixed. If you want to install manually, make sure you install from `st3-v2.2.0` tag.

**Comment by arshmakker** [comment]
I too am facing a similar issue. Package control is not able to find 'SublimeCodeIntel'
My sublime version
<img width="283" alt="screen shot 2017-10-20 at 4 47 05 pm" src="https://user-images.githubusercontent.com/6174092/31818595-6bfd81ec-b5b6-11e7-8a74-411b4a948784.png">
Let me know if there is any other information I can provide to fix this issue.

**Comment by Kronuz** [comment]
Should be fixed now, please try again.

**Comment by arshmakker** [comment]
Worked, perfectly !
