### ISSUE TITLE
Popup styles

### ISSUE THREAD

**Issue by natanfelles** [SublimeCodeIntel/SublimeCodeIntel#644]
What about to add support for styled popups like [on this image](https://github.com/spectacles/CodeComplice/issues/54)?

And, if possible, also run the HTML tags inside the docs...

Please, see the [docs image](https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/559#issuecomment-340274423).

**Comment by natanfelles** [comment]
And, if possible, a way to [show the docs while typing like Atom and PhpStorm](https://github.com/bcit-ci/CodeIgniter4/pull/624).

Thank you! 😃

**Comment by mrliptontea** [comment]
This can be done fairly easily with the use of [mdpopups](https://github.com/facelessuser/sublime-markdown-popups).

It boils down to preparing correct markdown like `"```{}\n{}\n```\n".format(lang, signature)`.

Packages can define dependencies on other packages through a `dependencies.json` file, see [documentation](https://packagecontrol.io/docs/dependencies).

A similar project could be an inspiration https://github.com/tomv564/LSP.

**Comment by natanfelles** [comment]
![captura de tela de 2018-02-23 03-10-24](https://user-images.githubusercontent.com/3011423/36580640-d05259a8-1847-11e8-860a-99340cf431a2.png)


Closing since something like that already occurs on version 3. Thank you!
