### ISSUE TITLE
SublimeCodeIntel pipes don't work on Windows

### ISSUE THREAD

**Issue by deathaxe** [SublimeCodeIntel/SublimeCodeIntel#645]
I found one reason for named pipes not to work on Windows.

The `str(...)` in the following line must be replaced by `bytes(...)` to work properly with python 3.

https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/3b55dc31baf99814f5d18ab3d90637985ea76d65/libs/win32_named_pipe.py#L215

With that replaced codeintel still closes and restarts repetitively with the same issue on the other end. Did not find a solution yet.

Console shows:

```
Consider setting library_path.
a bytes-like object is required, not 'str' (c:\apps\python36\lib\site-packages\codeintel\codeintel2\oop\driver.py:541 in start)
Error handling unsolicited response
Error reading data from OOP CodeIntel: [WinError 109] Die Pipe wurde beendet.
```

**Comment by Kronuz** [comment]
Problem was not with Windows pipes, something else was wrong. Should be fixed in v3.0.0-beta.38. Note you will also need to upgrade CodeIntel to v2.0.0-beta.35 (`pip install -U --pre CodeIntel`)

**Comment by deathaxe** [comment]
I still think `str(buf.value)` must be changed to `bytes(buf.value)`, but can't check it as codeintel no longer starts after latest upgrade.

This i what the `~/.codeintel/codeintel.log` contains:

```
ERROR:codeintel.cpp:Consider setting library_path.
Exception in thread Codeintel OOP Driver Send Thread:
Traceback (most recent call last):
  File "c:\apps\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\apps\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\apps\python36\lib\site-packages\codeintel\codeintel2\oop\driver.py", line 303, in _send_proc
    self.fd_out.write(buf_len)
  File "c:\apps\python36\lib\site-packages\codeintel\win32_named_pipe.py", line 188, in write
    raise ctypes.WinError(errno)
OSError: [WinError 6] Das Handle ist ungültig.

```

**Comment by Kronuz** [comment]
That’s weird... in the latest upgrade I believe I changed three things:

First, the obvious removal of the problematic `str()` (`buf.value` is of type bytes already).

The way `libs` are imported (always as absolute imports now); so I dynamically added back the `libs` directory to the path, so `libs/process.py` is imported as `import process`, for example. (CodeIntel also includes and uses the exact same libs files, so imports must remain compatible for both SublimeCodeIntel and CodeIntel)

I also changed the way the CodeIntel executable is located. If the user doesn’t specifically adds a path, then `codeintel.exe` is tried to be located in a few common places.

**Comment by Kronuz** [comment]
Oh! Makes sense... adding `libs` directory won’t work as it comes packaged in a zip file (`.sublime-package`)

**Comment by Kronuz** [comment]
Please try again, need to upgrade both CodeIntel (to v2.0.0-beta.36) and SublimeCodeIntel (to v3.0.0-beta.39)

**Comment by deathaxe** [comment]
Evaluation works and the `str()` is gone.

> ... codeintel.exe is tried to be located in a few common places.

I saw those lookup paths and was worried about it to be the reason for codeintel.exe not to start on a first glance as python is installed on C:\Apps\python36 on my box. But your lookup seems to include the `%PATH%`. The executable is found.
