### ISSUE TITLE
[PHP] Not working on Windows 10 / Sublime 3143 / Python 3.6.1

### ISSUE THREAD

**Issue by imbrish** [SublimeCodeIntel/SublimeCodeIntel#647]
I installed `SublimeCodeIntel` some time ago and never managed to make it work. Both goto definition and autocomplete are failing me.

**For `v2.2.0` installed via Package Control**

Console:
```
+ Info: processing `PHP': please wait...
Could not import subprocess32 module, falling back to subprocess module
reloading .../.codeintel/codeintel.log
```

Log:
```
Starting logging SublimeCodeIntel v2.2.0 rev GIT-unknown (1496520546) on Tue Nov  7 12:57:33 2017
=================================================================================================
Updating indexes for 'PHP'... The first time this can take a while.
scan_purelang: path: '....\\app\\Http\\Controllers\\SyncController.php' lang: PHP
Doing CodeIntel for 'PHP' (hold on)...
lang_xml.py: async_eval_at_trg:
    Internal error: Unknown UDL-based XML completion type: 'defn'
done eval: error
Done 'PHP' CodeIntel! Full CodeIntel took 472ms
```

**For `v3.0.0-beta.40`**
```
ERROR:codeintel.cpp:Consider setting library_path.
ERROR:codeintel.tree:Unexpected error with evaluator: 'Illuminate\Http\Request' at synccontroller.php#8
Traceback (most recent call last):
  File "...\python36\lib\site-packages\codeintel\codeintel2\tree.py", line 331, in eval
    defns = self.eval_defns()
  File "...\python36\lib\site-packages\codeintel\codeintel2\tree_php.py", line 368, in eval_defns
    hit = self._hit_from_citdl(self.expr, start_scoperef)
  File "...\python36\lib\site-packages\codeintel\codeintel2\tree_php.py", line 889, in _hit_from_citdl
    hits, nconsumed = self._hits_from_first_part(tokens, scoperef)
  File "...\python36\lib\site-packages\codeintel\codeintel2\tree_php.py", line 1152, in _hits_from_first_part
    hits = self._hits_from_namespace(first_token, scoperef)
  File "...\python36\lib\site-packages\codeintel\codeintel2\tree_php.py", line 1123, in _hits_from_namespace
    libs = [self.buf.stdlib] + self.libs
  File "...\python36\lib\site-packages\codeintel\codeintel2\lang_php.py", line 1204, in stdlib
    return self.libs[-1]
  File "...\python36\lib\site-packages\codeintel\codeintel2\lang_php.py", line 1200, in libs
    return self.langintel.libs_from_buf(self)
  File "...\python36\lib\site-packages\codeintel\codeintel2\lang_php.py", line 927, in libs_from_buf
    libs += self._buf_indep_libs_from_env(env)
  File "...\python36\lib\site-packages\codeintel\codeintel2\lang_php.py", line 1074, in _buf_indep_libs_from_env
    = self._php_info_from_php(php, env)
  File "...\python36\lib\site-packages\codeintel\codeintel2\lang_php.py", line 980, in _php_info_from_php
    p = process.ProcessOpen(argv, env=env.get_all_envvars())
  File "...\python36\lib\site-packages\codeintel\process.py", line 581, in __init__
    creationflags=flags)
  File "...\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "...\python36\lib\site-packages\codeintel\process.py", line 399, in _execute_child
    startupinfo)
TypeError: environment can only contain strings
```

**Comment by Kronuz** [comment]
In CodeIntel 2, for SublimeCodeIntel 3, can you please check if commenting lines 499-509 of `...\python36\lib\site-packages\codeintel\process.py` fixes the problem?

**Comment by Kronuz** [comment]
This was also reported in https://github.com/SublimeCodeIntel/CodeIntel/issues/1, it should be fixed in CodeIntel `v2.0.0-rc.2` and SublimeCodeIntel `v3.0.0-rc.1`.

Please reopen if the problem persists after upgrading.

**Comment by imbrish** [comment]
After commenting out the lines at first error was gone, but goto definition wouldn't do nothing. The status would just flash, "SublimeCodeIntel : aborted". However after some time and a few restarts SublimeCodeIntel began to actually scan the project files (didn't happen before).

The process logged a few random errors (`BrokenPipeError: [WinError 232]`, `codeintel2.common.NotFoundInDatabase`, `FileExistsError: [WinError 183]`) and... code intel began to work, both goto and complete functions.

I tested it a bit, and after initial lagging it seems to work fine. The little exception is that paths of opened files are completely lowercased. Is that how it should work?

It also added a bunch of logs to sublime console (filled the buffer completely):
```
INFO: _hit_from_elem_imports:: ie: lookup ('service',) in <PHP extradirslib> => []
```

**Comment by imbrish** [comment]
@Kronuz when is `v3.0.0-rc.1` planned to be released? Also note the lowercased paths of opened files, is that normal behavior?

**Comment by Kronuz** [comment]
There's still no timing plan for release yet; I was hoping maybe make an installer for CodeIntel for Windows at least (so people doesn't have to install Python there), but I haven't got the time to check out how that could be done.

Paths lowercased? what do you mean? paths probably go through a normalization process; but I'd have to check that in other environments (linux, mac).

**Comment by imbrish** [comment]
If file with method definition is closed, it will open after `alt+click` but it's path (in side bar or window title) will be for example `some/dummy/path/classname.php`  instead of `Some/Dummy/Path/ClassName.php`.
