### ISSUE TITLE
Please stop by IRC/Gitter 

### ISSUE THREAD

**Issue by Naatan** [SublimeCodeIntel/SublimeCodeIntel#650]
Hey Kronuz, been trying to get in contact with you but alas to no avail. So trying a different channel. Would you kindly stop by IRC/Gitter to discuss your ECMAscript parser?

Thanks! :)

**Comment by Kronuz** [comment]
HI Nathan, I’ve been way too busy lately. I’ll stop by later this weekend or Monday. :)
