### ISSUE TITLE
Does SublimeCodeIntel support C/C++?

### ISSUE THREAD

**Issue by haferburg** [SublimeCodeIntel/SublimeCodeIntel#654]
On `https://github.com/SublimeCodeIntel/SublimeCodeIntel/blob/master/README.md` it says it does, but C and C++ are neither listed on http://www.sublimecodeintel.com/, nor in `codeintel_enabled_languages` in the default `SublimeCodeIntel.sublime-settings`. Is the README wrong?

**Comment by yafz** [comment]
So... it does not, I guess?

**Comment by haferburg** [comment]
My guess was that the latest release doesn't support it yet, but they're currently adding support in `master`.
