### ISSUE TITLE
Is repository alive?

### ISSUE THREAD

**Issue by UmutAlihan** [SublimeCodeIntel/SublimeCodeIntel#705]
Hi,

I have read the readme and it stated that contributions wanted for maintenance. I am considering deepdiving into codebase and contribute. But I need to know whether this repo is active or not?

Cheers

**Comment by robclancy** [comment]
Considering how many updates komodo edit codeintel has had it's a shame this plugin was never kept up to date. I guess the people who made it never needed sublime or this plugin anymore.

**Comment by ykqmain** [comment]
Now everyone seems to be turning to [LSP](https://github.com/sublimelsp/LSP)

**Comment by robclancy** [comment]
Thanks.

**Comment by UmutAlihan** [comment]
Many thanks as well!
