### ISSUE TITLE
Coffeescript support

### ISSUE THREAD

**Issue by dmmalam** [SublimeCodeIntel/SublimeCodeIntel#87]
Hey, 

Can the node.js / js completion work with coffeescript?

I've added this to my user config
    "codeintel_syntax_map":
    {
         "JavaScript": "Node.js",
      "CoffeeScript": "Node.js"
    },

And it seems like codeintel is working in the status bar, but the completion isn't working

Any ideas?

**Comment by Kuzirashi** [comment]
+1

**Comment by lpillonel** [comment]
+1

**Comment by MiincGu** [comment]
+1

**Comment by artkik700** [comment]
+1

**Comment by schrodincat** [comment]
+1
Support for CoffeeScript is still relevant and would be appreciated
